import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin,Car,CalendarCheck,Star,Zap,User,Menu,Navigation,Clock,ShieldCheck,RefreshCw} from 'lucide-react';
import './style.css';
const API='http://localhost:5000/api';
function App(){
 const [tab,setTab]=useState('home'),[parks,setParks]=useState([]),[bookings,setBookings]=useState([]),[dest,setDest]=useState('Chennai Central'),[rec,setRec]=useState(null),[loading,setLoading]=useState(false),[toast,setToast]=useState('');
 const load=async()=>{setParks(await (await fetch(API+'/parking')).json());setBookings(await (await fetch(API+'/bookings')).json())};
 useEffect(()=>{load()},[]);
 const recommend=async()=>{setLoading(true);let d=await (await fetch(API+'/recommend?destination='+encodeURIComponent(dest))).json();setRec(d.recommendation);setTab('ai');setLoading(false)};
 const book=async id=>{let r=await fetch(API+'/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parkingId:id,arrival:'Today 5:30 PM'})});let d=await r.json();if(!r.ok){setToast(d.error);return}setToast('Slot booked successfully ✓');await load();setTab('bookings');setTimeout(()=>setToast(''),2500)};
 return <div className="shell"><aside><div className="logo"><span>P</span>arkAI</div><nav>{[['home','Home',Car],['map','Smart Map',MapPin],['bookings','My Bookings',CalendarCheck],['ai','AI Recommendation',Star],['ev','EV Charging',Zap],['profile','Profile',User]].map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={18}/>{label}</button>)}</nav><div className="asideNote"><ShieldCheck size={18}/><b>Smart mobility</b><small>Find the best parking before parking-related traffic begins.</small></div></aside>
 <main><header><div><small>ParkAI • Smart Urban Mobility</small><h1>{tab==='home'?'Good afternoon 👋':tab.replace('bookings','My Bookings').replace('ai','AI Recommendation').replace('map','Smart Map')}</h1></div><div className="loc"><MapPin size={16}/> Chennai, India</div></header>
 {tab==='home'&&<><section className="hero"><div><label>AI-POWERED PARKING</label><h2>Find. Book.<br/><em>Park. Move.</em></h2><p>Real-time parking, traffic-aware recommendations and EV charging availability in one platform.</p><button className="primary" onClick={recommend}><Star size={17}/> Find Best Parking</button></div><div className="heroMark">P<span>AI</span></div></section><div className="search"><MapPin/><input value={dest} onChange={e=>setDest(e.target.value)} placeholder="Where do you want to park?"/><button onClick={recommend}>{loading?'Finding…':'Find Parking'}</button></div><Stats parks={parks}/><h2 className="sect">Nearby parking <button onClick={()=>setTab('map')}>View map →</button></h2><ParkList parks={parks} onBook={book}/></>}
 {tab==='map'&&<MapScreen parks={parks}/>}
 {tab==='bookings'&&<BookingScreen bookings={bookings}/>}
 {tab==='ai'&&<AI rec={rec||parks[0]} onBook={book}/>}
 {tab==='ev'&&<EV parks={parks}/>}
 {tab==='profile'&&<Profile/>}
 </main>{toast&&<div className="toast">{toast}</div>}</div>
}
function Stats({parks}){return <div className="stats"><div><b>{parks.reduce((a,p)=>a+p.available,0)}</b><small>Free Slots</small></div><div><b>{parks.length}</b><small>Parking Areas</small></div><div><b>{parks.reduce((a,p)=>a+p.evAvailable,0)}</b><small>EV Chargers</small></div><div><b>24%</b><small>Traffic Saved*</small></div></div>}
function ParkList({parks,onBook}){return <div className="cards">{parks.map(p=><div className="park"><div className="icon">🅿️</div><div className="grow"><h3>{p.name}</h3><p>{p.distance||'0.8 km'} • {p.traffic} traffic • ₹{p.price}/hr</p><small>🅿️ {p.available} free &nbsp; ⚡ {p.evAvailable} chargers</small></div><button className="outline" disabled={!p.available} onClick={()=>onBook(p.id)}>{p.available?'Book':'Full'}</button></div>)}</div>}
function MapScreen({parks}){return <><div className="sect"><div><h2>Smart Parking Map</h2><p>Demo real-time network • Connect a map provider for live navigation.</p></div><RefreshCw onClick={()=>location.reload()}/></div><div className="map">{parks.map((p,i)=><div className={'mapPin pin'+i} title={p.name}>{p.evAvailable?'⚡':'P'}<small>{p.available}</small></div>)}<div className="mapTitle">CHENNAI CENTRAL</div></div><div className="legend">🟢 Available &nbsp; 🟡 Limited &nbsp; 🔴 Full &nbsp; ⚡ EV</div></>}
function BookingScreen({bookings}){return <><div className="sect"><div><h2>My Bookings</h2><p>Reserved parking spaces</p></div></div>{bookings.length?<div className="cards">{bookings.map(b=><div className="booking"><div><label>CONFIRMED</label><h3>{b.parkingName}</h3><p>Slot <b>{b.slot}</b> • {b.arrival} • ₹{b.price}/hr</p></div><button className="primary"><Navigation size={16}/> Track</button></div>)}</div>:<div className="empty">No bookings yet. Find a parking space and reserve it.</div>}</>}
function AI({rec,onBook}){if(!rec)return <div className="empty">Loading parking data…</div>;return <><div className="aiBox"><div className="aiIcon">✦</div><div className="grow"><label>AI RECOMMENDED</label><h2>{rec.name}</h2><p>{rec.reason||'Best overall parking option from available demo data.'}</p></div><strong>{rec.score||91}%</strong></div><div className="factors"><div><b>🟢 {rec.traffic}</b><small>Traffic</small></div><div><b>{rec.available}</b><small>Slots</small></div><div><b>{rec.walking||180}m</b><small>Walking</small></div><div><b>{rec.evAvailable} ⚡</b><small>Chargers</small></div></div><button className="primary wide" onClick={()=>onBook(rec.id)}>Reserve recommended slot</button><div className="note"><Clock/> AI score combines availability, traffic, EV charger status, walking distance and parking price.</div></>}
function EV({parks}){return <><div className="sect"><div><h2>EV Charging</h2><p>Live charger status in the demo network</p></div></div><div className="cards">{parks.map(p=><div className="park"><div className="icon blue">⚡</div><div className="grow"><h3>{p.name}</h3><p>{p.evAvailable} of {p.evTotal} chargers available</p><div className="bar"><i style={{width:`${p.evAvailable/p.evTotal*100}%`}}/></div><b className="green">{p.evAvailable} FREE</b></div>)}</div></>}
function Profile(){return <div className="profile"><div className="avatar">P</div><h2>ParkAI User</h2><p>Smart parking preferences</p><div className="settings"><div>🚗 Vehicle <b>EV • TN 01 XX 0000</b></div><div>⚡ EV preference <b>Enabled</b></div><div>🔔 Notifications <b>On</b></div><div>◷ Booking history <b>Live from demo backend</b></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);